name: smart_interview_app
description: A Smart AI Interview Preparation App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP requests to Node backend
  http: ^1.2.2

  # State management
  provider: ^6.1.2

  # JSON models
  json_annotation: ^4.9.0

  # Fonts
  google_fonts: ^6.2.1

  # Loaders
  flutter_spinkit: ^5.2.0

  # .env variables (backend URL)
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env